<div class="flex justify-center p-12 space-y-4 max-w-10xl">
    <div class="flex-col w-10/12 max-w-5xl text-center bg-gray-100 rounded-lg shadow-lg p-8">
        <h1 class="text-7xl font-bold mb-12">Model A</h1>
        <p class="font-mono text-lg py-2 px-4 text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis luctus lorem, a sodales velit. Cras rutrum mi ut tincidunt cursus. Pellentesque tempus porttitor fermentum. Donec tincidunt est vel lacus ornare auctor. Etiam mattis metus in fringilla euismod. Phasellus vitae enim felis. Aliquam lacus sem, mattis at ligula id, porttitor hendrerit risus. Cras gravida libero lacinia lacus fermentum congue. Vestibulum consectetur pulvinar velit, nec ultricies diam volutpat eget. Quisque lorem dolor, dictum dignissim scelerisque eget, gravida commodo ante. Vivamus eu nisi mauris. Etiam odio metus, malesuada at ligula sit amet, fringilla varius quam. Etiam nec est eu arcu facilisis elementum feugiat a augue. Donec commodo vel mauris ac tristique. Quisque scelerisque massa turpis, quis imperdiet tellus luctus accumsan. </p>
        <p class="font-mono text-lg py-2 px-4 text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis luctus lorem, a sodales velit. Cras rutrum mi ut tincidunt cursus. Pellentesque tempus porttitor fermentum. Donec tincidunt est vel lacus ornare auctor. Etiam mattis metus in fringilla euismod. Phasellus vitae enim felis. Aliquam lacus sem, mattis at ligula id, porttitor hendrerit risus. Cras gravida libero lacinia lacus fermentum congue. Vestibulum consectetur pulvinar velit, nec ultricies diam volutpat eget. Quisque lorem dolor, dictum dignissim scelerisque eget, gravida commodo ante. Vivamus eu nisi mauris. Etiam odio metus, malesuada at ligula sit amet, fringilla varius quam. Etiam nec est eu arcu facilisis elementum feugiat a augue. Donec commodo vel mauris ac tristique. Quisque scelerisque massa turpis, quis imperdiet tellus luctus accumsan. </p>
        <p class="font-mono text-lg py-2 px-4 text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis luctus lorem, a sodales velit. Cras rutrum mi ut tincidunt cursus. Pellentesque tempus porttitor fermentum. Donec tincidunt est vel lacus ornare auctor. Etiam mattis metus in fringilla euismod. Phasellus vitae enim felis. Aliquam lacus sem, mattis at ligula id, porttitor hendrerit risus. Cras gravida libero lacinia lacus fermentum congue. Vestibulum consectetur pulvinar velit, nec ultricies diam volutpat eget. Quisque lorem dolor, dictum dignissim scelerisque eget, gravida commodo ante. Vivamus eu nisi mauris. Etiam odio metus, malesuada at ligula sit amet, fringilla varius quam. Etiam nec est eu arcu facilisis elementum feugiat a augue. Donec commodo vel mauris ac tristique. Quisque scelerisque massa turpis, quis imperdiet tellus luctus accumsan. </p>
        <p class="font-mono text-lg py-2 px-4 text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis luctus lorem, a sodales velit. Cras rutrum mi ut tincidunt cursus. Pellentesque tempus porttitor fermentum. Donec tincidunt est vel lacus ornare auctor. Etiam mattis metus in fringilla euismod. Phasellus vitae enim felis. Aliquam lacus sem, mattis at ligula id, porttitor hendrerit risus. Cras gravida libero lacinia lacus fermentum congue. Vestibulum consectetur pulvinar velit, nec ultricies diam volutpat eget. Quisque lorem dolor, dictum dignissim scelerisque eget, gravida commodo ante. Vivamus eu nisi mauris. Etiam odio metus, malesuada at ligula sit amet, fringilla varius quam. Etiam nec est eu arcu facilisis elementum feugiat a augue. Donec commodo vel mauris ac tristique. Quisque scelerisque massa turpis, quis imperdiet tellus luctus accumsan. </p>
        <p class="font-mono text-lg py-2 px-4 text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis luctus lorem, a sodales velit. Cras rutrum mi ut tincidunt cursus. Pellentesque tempus porttitor fermentum. Donec tincidunt est vel lacus ornare auctor. Etiam mattis metus in fringilla euismod. Phasellus vitae enim felis. Aliquam lacus sem, mattis at ligula id, porttitor hendrerit risus. Cras gravida libero lacinia lacus fermentum congue. Vestibulum consectetur pulvinar velit, nec ultricies diam volutpat eget. Quisque lorem dolor, dictum dignissim scelerisque eget, gravida commodo ante. Vivamus eu nisi mauris. Etiam odio metus, malesuada at ligula sit amet, fringilla varius quam. Etiam nec est eu arcu facilisis elementum feugiat a augue. Donec commodo vel mauris ac tristique. Quisque scelerisque massa turpis, quis imperdiet tellus luctus accumsan. </p>
    </div>
</div>