<div class="flex justify-center p-12 space-y-4 max-w-10xl">
    <div class="flex-col w-10/12 max-w-5xl text-center bg-gray-100 rounded-lg shadow-lg p-8">
        <h1 class="text-7xl font-bold mb-12">Theodore's CS180 Project</h1>
        <p class="font-mono text-lg py-2 px-4 text-justify">This website will showcase the group Theodore's output for the CS180 project where the task was to make two versionf of machine learning models to predict the diseases of a potato plant based on an input image.</p>
        <p class="font-mono text-lg py-2 px-4 text-justify">There have been two models developed as different solutions or approaches to the problem called Model A and Model B:</p>
        <ul class="list-disc list-inside text-left font-mono text-lg pl-8 py-2 pr-4">
            <li>Model A: A Convolutional Neural Network (CNN) based model that uses a traditional approach to image classification.</li>
            <li>Model B: A Vision Transformer (ViT) based model that employs a transformer architecture for image classification.</li>
        </ul>
        
        
        <p class="font-mono text-5xl font-bold py-2 px-4">Sample Images</p>
        <p class="font-mono text-lg py-2 px-4 text-justify">Below is a sample healthy potato leaf:</p>
        <img src="/healthy.jpeg" alt="healthy" class="w-full h-auto my-4 rounded-lg shadow-lg">
        <p class="font-mono text-lg py-2 px-4 text-justify">Below is a leaf infected with bacteria which can be spotted by the curling of the leaves and small brown spots:</p>
        <img src="/bacteria.jpeg" alt="bacteria" class="w-full h-auto my-4 rounded-lg shadow-lg">
        <p class="font-mono text-lg py-2 px-4 text-justify">Below is a leaf infected with phytopthora which has subtle indicators but is commonly spotted by the browning and wilting of a spot:</p>
        <img src="/phytopthora.jpeg" alt="phytopthora" class="w-full h-auto my-4 rounded-lg shadow-lg">
        
        <p class="font-mono text-lg py-2 px-4 text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis luctus lorem, a sodales velit. Cras rutrum mi ut tincidunt cursus. Pellentesque tempus porttitor fermentum. Donec tincidunt est vel lacus ornare auctor. Etiam mattis metus in fringilla euismod. Phasellus vitae enim felis. Aliquam lacus sem, mattis at ligula id, porttitor hendrerit risus. Cras gravida libero lacinia lacus fermentum congue. Vestibulum consectetur pulvinar velit, nec ultricies diam volutpat eget. Quisque lorem dolor, dictum dignissim scelerisque eget, gravida commodo ante. Vivamus eu nisi mauris. Etiam odio metus, malesuada at ligula sit amet, fringilla varius quam. Etiam nec est eu arcu facilisis elementum feugiat a augue. Donec commodo vel mauris ac tristique. Quisque scelerisque massa turpis, quis imperdiet tellus luctus accumsan. </p>
        <p class="font-mono text-lg py-2 px-4 text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis luctus lorem, a sodales velit. Cras rutrum mi ut tincidunt cursus. Pellentesque tempus porttitor fermentum. Donec tincidunt est vel lacus ornare auctor. Etiam mattis metus in fringilla euismod. Phasellus vitae enim felis. Aliquam lacus sem, mattis at ligula id, porttitor hendrerit risus. Cras gravida libero lacinia lacus fermentum congue. Vestibulum consectetur pulvinar velit, nec ultricies diam volutpat eget. Quisque lorem dolor, dictum dignissim scelerisque eget, gravida commodo ante. Vivamus eu nisi mauris. Etiam odio metus, malesuada at ligula sit amet, fringilla varius quam. Etiam nec est eu arcu facilisis elementum feugiat a augue. Donec commodo vel mauris ac tristique. Quisque scelerisque massa turpis, quis imperdiet tellus luctus accumsan. </p>
        <p class="font-mono text-lg py-2 px-4 text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis luctus lorem, a sodales velit. Cras rutrum mi ut tincidunt cursus. Pellentesque tempus porttitor fermentum. Donec tincidunt est vel lacus ornare auctor. Etiam mattis metus in fringilla euismod. Phasellus vitae enim felis. Aliquam lacus sem, mattis at ligula id, porttitor hendrerit risus. Cras gravida libero lacinia lacus fermentum congue. Vestibulum consectetur pulvinar velit, nec ultricies diam volutpat eget. Quisque lorem dolor, dictum dignissim scelerisque eget, gravida commodo ante. Vivamus eu nisi mauris. Etiam odio metus, malesuada at ligula sit amet, fringilla varius quam. Etiam nec est eu arcu facilisis elementum feugiat a augue. Donec commodo vel mauris ac tristique. Quisque scelerisque massa turpis, quis imperdiet tellus luctus accumsan. </p>
    </div>
</div>